/**
 * Code Execution Types
 *
 * Defines types for code execution within AI flow stages where LLMs write TypeScript
 * code that calls function APIs in a sandboxed environment.
 */

/**
 * Virtual filesystem API available to both AI code and function implementations
 */
export type FsApi = {
  read: (path: string) => Promise<string>;
  write: (path: string, content: string) => Promise<void>;
  exists: (path: string) => Promise<boolean>;
  list: (path: string) => Promise<string[]>;
};

/**
 * Console API available to AI code
 */
export type ConsoleApi = {
  log: (...args: unknown[]) => void;
  warn: (...args: unknown[]) => void;
  error: (...args: unknown[]) => void;
};

/**
 * Context passed to function implementations (NOT visible to AI)
 *
 * Functions receive this context object as their second parameter,
 * giving them access to filesystem, flow context, external deps, and output accumulator.
 */
export type FunctionContext<
  TCtx extends Record<string, unknown>,
  TDeps,
  TOutput,
> = {
  /** Virtual filesystem - shared with AI */
  fs: FsApi;
  /** Flow context - shared with AI, can be mutated */
  ctx: TCtx;
  /** External dependencies (db, logger, etc.) - NOT visible to AI */
  deps: TDeps;
  /** Output accumulator - functions write structured results here - NOT visible to AI */
  output: TOutput;
};

/**
 * Validation result from typia or manual validation
 */
export type CodeFunctionValidation<T> =
  | {
      success: true;
      data: T;
    }
  | {
      success: false;
      errors: Array<{
        path: string;
        expected: string;
        value: unknown;
      }>;
    };

/**
 * A code function is a self-describing async function that can be called from AI-generated code.
 *
 * Code functions are typically created by the `.tool.ts` plugin which:
 * 1. Extracts JSDoc descriptions
 * 2. Generates typia validators from input types
 * 3. Generates TypeScript declarations for the AI
 * 4. Extracts deps type from the second parameter
 *
 * They can also be created manually using `codeFunction()`.
 *
 * @example
 * ```typescript
 * // Via plugin - write a .tool.ts file:
 * // routines.tool.ts
 * import { defineCodeBinding } from '@inkibra/ai-flow/codemode';
 *
 * /**
 *  * Fetches a user by ID from the database
 *  *\/
 * export const fetchUser = defineCodeBinding(
 *   async function fetchUser(
 *     { userId }: { userId: string },
 *     { deps }: { deps: RoutineDeps }
 *   ): Promise<User> {
 *     deps.logger.debug('Fetching user', { userId });
 *     return deps.db.getUser(userId);
 *   },
 * );
 *
 * // Via manual creation:
 * const fetchUser = codeFunction({
 *   description: 'Fetches a user by ID',
 *   validate: typia.createValidate<{ userId: string }>(),
 *   fn: async ({ userId }, { deps }) => deps.db.getUser(userId),
 * });
 * ```
 */
export type CodeFunction<TParams, TResult, TDeps = unknown> = {
  /** Human-readable description shown to the AI */
  description: string;
  /** TypeScript declaration string shown to the AI (params and return only) */
  declaration: string;
  /** Validates input parameters (generated by typia or provided manually) */
  validate: (input: unknown) => CodeFunctionValidation<TParams>;
  /** The actual function implementation - receives params and FunctionContext */
  fn: <TCtx extends Record<string, unknown>, TOutput>(
    params: TParams,
    context: FunctionContext<TCtx, TDeps, TOutput>,
  ) => Promise<TResult>;
};

/**
 * Options for creating a code function manually
 */
export type CodeFunctionOptions<TParams, TResult, TDeps = unknown> = {
  /** Human-readable description shown to the AI */
  description: string;
  /** TypeScript declaration string (optional - will be inferred if not provided) */
  declaration?: string;
  /** Validates input parameters (from typia.createValidate) */
  validate: (input: unknown) => CodeFunctionValidation<TParams>;
  /** The actual function implementation */
  fn: <TCtx extends Record<string, unknown>, TOutput>(
    params: TParams,
    context: FunctionContext<TCtx, TDeps, TOutput>,
  ) => Promise<TResult>;
};

/**
 * Record of a function call made during code execution
 */
export type FunctionCall = {
  /** Name of the function that was called */
  name: string;
  /** Arguments passed to the function */
  args: unknown;
  /** Timestamp when the call was made */
  timestamp: number;
  /** Result of the function call (if successful) */
  result?: unknown;
  /** Error message (if failed) */
  error?: string;
  /** Duration in milliseconds */
  duration: number;
};

/**
 * Result of code execution in the sandbox
 */
export type ExecutionResult<TCtx extends Record<string, unknown>, TOutput> =
  | {
      /** Execution succeeded */
      success: true;
      /** The modified context object */
      ctx: TCtx;
      /** All files in the virtual filesystem after execution */
      files: Record<string, string>;
      /** The output accumulator (what functions wrote) */
      output: TOutput;
      /** Console log output from the code */
      logs: string[];
      /** Function calls made during execution */
      calls: FunctionCall[];
      /** Execution duration in milliseconds */
      duration: number;
    }
  | {
      /** Execution failed */
      success: false;
      /** The error that occurred */
      error: Error;
      /** The context at time of error (may be partially mutated) */
      ctx: TCtx;
      /** Files at time of error */
      files: Record<string, string>;
      /** The output accumulator at time of error (may be partially filled) */
      output: TOutput;
      /** Console log output before the error */
      logs: string[];
      /** Function calls made before the error */
      calls: FunctionCall[];
      /** Execution duration in milliseconds */
      duration: number;
    };

/**
 * Sandbox configuration options
 */
export type SandboxConfig = {
  /** Maximum execution time in milliseconds (default: 30000) */
  timeout?: number;
  /** Maximum size of a single file in bytes (default: 10MB) */
  maxFileSize?: number;
  /** Maximum total filesystem size in bytes (default: 100MB) */
  maxTotalSize?: number;
};

/**
 * Configuration for code execution within a stage
 *
 * When added to a stage, this enables the LLM to call an `execute` tool
 * that runs TypeScript code with access to the configured functions.
 *
 * @example
 * ```typescript
 * const stage = createAiOutputStage('generateRoutine', {
 *   model: 'gpt-4',
 *
 *   codeExecution: {
 *     functions: { fetchUser, commitRoutine },
 *
 *     mount: (ctx) => ({
 *       '/input/exercises.json': JSON.stringify(ctx.exercises),
 *     }),
 *
 *     output: () => ({
 *       routine: null as Routine | null,
 *       routineId: null as string | null,
 *     }),
 *   },
 *
 *   // ... rest of stage config
 * });
 * ```
 */
export type CodeExecutionConfig<
  TCtx extends Record<string, unknown>,
  TOutput,
  TFunctions extends Record<string, CodeFunction<any, any, any>>,
> = {
  /** Code functions available to the AI-generated code */
  functions: TFunctions;
  /** Mount files into the virtual filesystem before execution */
  mount?: (ctx: TCtx) => Record<string, string>;
  /** Create the output accumulator (defines shape for type safety) */
  output?: () => TOutput;
  /** Sandbox configuration */
  sandbox?: SandboxConfig;
  /** Control which globals are exposed to AI code */
  expose?: {
    ctx?: boolean;
    fs?: boolean;
    console?: boolean;
  };
  /**
   * Factory that produces deps for code function implementations.
   * When provided, these deps are passed to function implementations instead of
   * the flow-level deps. This allows codeExecution configs to carry their own
   * dependencies (e.g., exercise search adapters) independently of the flow's deps type.
   */
  deps?: () => unknown;
};

/**
 * Extract the deps type from a CodeFunction
 */
export type ExtractFunctionDeps<F> = F extends CodeFunction<any, any, infer D>
  ? D
  : never;

/**
 * Extract the combined deps type from all functions in a record
 */
export type ExtractAllFunctionDeps<
  TFunctions extends Record<string, CodeFunction<any, any, any>>,
> = {
  [K in keyof TFunctions]: ExtractFunctionDeps<TFunctions[K]>;
}[keyof TFunctions];
