/**
 * @inkibra/storybook - Bun Plugin
 *
 * Provides the `virtual:storybook` module that exports the story manifest
 * and dynamic import map.
 */

import { type BunPlugin, plugin } from 'bun';
import type { StorybookConfig } from './config';
import type { DiscoveredFile } from './discovery';
import { discoverStories } from './discovery';
import type { StoryManifest } from './types';

// ============================================================================
// Types
// ============================================================================

export type StorybookPluginOptions = {
  /**
   * Package root directory.
   * Defaults to process.cwd().
   */
  packageRoot?: string;

  /**
   * Override storybook config instead of loading from file.
   */
  config?: StorybookConfig;

  /**
   * Whether to log warnings during discovery.
   * Defaults to true.
   */
  logWarnings?: boolean;
};

// ============================================================================
// Virtual Module Generation
// ============================================================================

/**
 * Generate the virtual module source code.
 */
function generateVirtualModule(
  manifest: StoryManifest,
  files: DiscoveredFile[],
  packageRoot: string,
): string {
  // Generate import map entries
  // Each entry maps fileId to a dynamic import function
  // Use absolute paths since the virtual module's location is not the package root
  const importEntries = files.map((file) => {
    // Use absolute path to ensure correct resolution from virtual module
    const importPath = file.absolutePath;
    return `  '${file.fileId}': () => import('${importPath}')`;
  });

  return `
// Auto-generated by @inkibra/storybook plugin
// Do not edit manually
// Package root: ${packageRoot}

export const manifest = ${JSON.stringify(manifest, null, 2)} as const;

export type Manifest = typeof manifest;

export const importModuleByFileId = {
${importEntries.join(',\n')}
};
`.trim();
}

// ============================================================================
// Bun Plugin
// ============================================================================

/**
 * Register the storybook Bun plugin.
 *
 * @example
 * ```ts
 * // In your entry file or preload
 * import { storybookPlugin } from '@inkibra/storybook/plugin';
 *
 * storybookPlugin({
 *   packageRoot: import.meta.dir,
 * });
 * ```
 */
export function storybookPlugin(options: StorybookPluginOptions = {}): void {
  const packageRoot = options.packageRoot ?? process.cwd();
  const logWarnings = options.logWarnings ?? true;

  // Cache for the generated module
  let cachedModule: string | null = null;

  plugin({
    name: '@inkibra/storybook',
    setup(build) {
      // Handle virtual:storybook imports
      build.onResolve({ filter: /^virtual:storybook$/ }, () => {
        return {
          path: 'virtual:storybook',
          namespace: 'storybook-virtual',
        };
      });

      build.onLoad(
        { filter: /.*/, namespace: 'storybook-virtual' },
        async () => {
          // Return cached module if available
          if (cachedModule) {
            return {
              contents: cachedModule,
              loader: 'ts',
            };
          }

          // Discover stories
          const result = await discoverStories(packageRoot, options.config);

          // Log warnings
          if (logWarnings && result.warnings.length > 0) {
            console.warn('[storybook] Discovery warnings:');
            for (const warning of result.warnings) {
              console.warn(`  - ${warning}`);
            }
          }

          // Generate and cache the module
          cachedModule = generateVirtualModule(
            result.manifest,
            result.files,
            packageRoot,
          );

          return {
            contents: cachedModule,
            loader: 'ts',
          };
        },
      );
    },
  });
}

// ============================================================================
// Bun.build() Plugin (for bundling)
// ============================================================================

/**
 * Create a BunPlugin for use with Bun.build().
 *
 * Unlike storybookPlugin() which registers globally, this returns a plugin
 * object that can be passed to Bun.build()'s plugins array.
 *
 * @example
 * ```ts
 * import { createStorybookBuildPlugin } from '@inkibra/storybook/plugin';
 *
 * const result = await Bun.build({
 *   entrypoints: ['./src/index.ts'],
 *   plugins: [createStorybookBuildPlugin({ packageRoot: './my-package' })],
 * });
 * ```
 */
export function createStorybookBuildPlugin(
  options: StorybookPluginOptions = {},
): BunPlugin {
  const packageRoot = options.packageRoot ?? process.cwd();
  const logWarnings = options.logWarnings ?? true;

  // Cache for the generated module
  let cachedModule: string | null = null;

  return {
    name: '@inkibra/storybook-build',
    setup(build) {
      // Handle virtual:storybook imports
      build.onResolve({ filter: /^virtual:storybook$/ }, () => {
        return {
          path: 'virtual:storybook',
          namespace: 'storybook-virtual',
        };
      });

      build.onLoad(
        { filter: /.*/, namespace: 'storybook-virtual' },
        async () => {
          // Return cached module if available
          if (cachedModule) {
            return {
              contents: cachedModule,
              loader: 'ts',
            };
          }

          // Discover stories
          const result = await discoverStories(packageRoot, options.config);

          // Log warnings
          if (logWarnings && result.warnings.length > 0) {
            console.warn('[storybook] Discovery warnings:');
            for (const warning of result.warnings) {
              console.warn(`  - ${warning}`);
            }
          }

          // Generate and cache the module
          cachedModule = generateVirtualModule(
            result.manifest,
            result.files,
            packageRoot,
          );

          return {
            contents: cachedModule,
            loader: 'ts',
          };
        },
      );
    },
  };
}

// ============================================================================
// Standalone Discovery (for use outside Bun plugin context)
// ============================================================================

/**
 * Discover stories and return the manifest.
 * Use this for scripts, tests, or other contexts where the plugin isn't used.
 */
export async function getManifest(
  packageRoot: string = process.cwd(),
  configOverride?: StorybookConfig,
): Promise<{ manifest: StoryManifest; warnings: string[] }> {
  const result = await discoverStories(packageRoot, configOverride);
  return {
    manifest: result.manifest,
    warnings: result.warnings,
  };
}

/**
 * Generate the virtual module source for writing to disk.
 * Useful for pre-generating the manifest during build.
 */
export async function generateManifestModule(
  packageRoot: string = process.cwd(),
  configOverride?: StorybookConfig,
): Promise<string> {
  const result = await discoverStories(packageRoot, configOverride);
  return generateVirtualModule(result.manifest, result.files, packageRoot);
}
