/**
 * Preview-based Scheduler Types (spec §20)
 *
 * The scheduler receives impulse submissions with selected previews,
 * generates ordering candidates for concurrent impulses, and decides
 * which to commit/drop/defer.
 */

import type { ResponsePlan } from '@inkibra/ai-sandbox-computer';
import type { ImpulseUrgency } from '../impulse/types';

/**
 * An impulse submission to the scheduler — contains the selected preview
 * from the impulse stage's preview_exec tool.
 */
export type PendingImpulseSubmission = {
  impulseId: string;
  /** The lane this impulse belongs to */
  lane: string;
  /** Target lanes for response plans (from plan_response lane field) */
  targetLanes: string[];
  thinking: string;
  urgency: ImpulseUrgency;
  submittedAt: Date;
  /** The selected preview record (null = observation-only, no commit needed) */
  selectedPreview: PreviewSummary | null;
};

/**
 * Summary of a preview for scheduler context — the scheduler doesn't need
 * the full code, just the outputs.
 */
export type PreviewSummary = {
  execId: string;
  /** Captured stdout from the preview run */
  stdout: string;
  /** Response plans proposed by plan_response() */
  responsePlans: ResponsePlan[];
  /** Files written during preview */
  filesWritten: string[];
  /** Whether the preview had errors */
  hasError: boolean;
};

/**
 * An ordering candidate for concurrent impulses.
 * Generated by the framework, presented to the scheduler LLM.
 */
export type OrderingCandidate = {
  id: string;
  /** Impulse IDs in execution order */
  impulseOrder: string[];
  /** Combined stdout from running impulses in this order */
  combinedStdout: string;
  /** Combined response plans */
  combinedResponsePlans: ResponsePlan[];
  /** Combined files written */
  combinedFilesWritten: string[];
};

/**
 * Scheduler decision output (spec §20.4).
 *
 * The scheduler selects which impulses to commit (in a valid ordering),
 * which to drop, and optionally dispatches a new impulse.
 * Any impulse not in consumed or dropped is automatically deferred.
 */
export type SchedulerCommitDecision = {
  thinking: string;
  /** Impulse IDs to commit, in execution order (must match a valid ordering candidate) */
  consumedImpulses: string[];
  /** Impulse IDs to permanently discard */
  droppedImpulses: string[];
  /** Optional: dispatch a new impulse (omitted when budget exhausted) */
  dispatchImpulse?: {
    reason: string;
  };
};

/**
 * Result of committing a preview against real state.
 */
export type PreviewCommitResult = {
  committed: boolean;
  impulseIds: string[];
  responsePlans: ResponsePlan[];
  filesWritten: string[];
  error?: string;
};
