/**
 * Client Stub Plugin
 *
 * Intercepts imports to .client.tsx files and extracts only the buildConfig,
 * preventing browser code from being loaded on the server.
 *
 * The plugin:
 * 1. Reads the .client.tsx file
 * 2. Extracts the buildConfig via regex
 * 3. Injects the entryPoint (file path)
 * 4. Returns a stub module with only the config
 *
 * This allows the server to import { buildConfig } from './app.client.tsx'
 * without loading React, DOM APIs, or other browser-only code.
 */

import * as fs from 'node:fs';
import type { BunPlugin } from 'bun';

/**
 * Extract the buildConfig object from a client file's content.
 *
 * Looks for: defineClientBuild({ ... })
 *
 * @param content - The file content
 * @returns The extracted config object as a string, or null if not found
 */
function extractBuildConfig(content: string): string | null {
  // Match defineClientBuild({ ... }) with nested braces support
  // This regex handles:
  // - Single line: defineClientBuild({ clientDir: 'tempo' })
  // - Multi-line with nested objects: defineClientBuild({ plugins: { ... } })
  const match = content.match(
    /defineClientBuild\s*\(\s*(\{[\s\S]*?\})\s*\)(?=\s*;|\s*$|\s*\n)/,
  );

  if (match?.[1]) {
    return match[1];
  }

  // Fallback: try to match a simpler pattern
  const simpleMatch = content.match(
    /defineClientBuild\s*\(\s*(\{[^}]+\})\s*\)/,
  );
  return simpleMatch?.[1] ?? null;
}

/**
 * Generate stub module code with extracted buildConfig.
 *
 * @param configObject - The extracted config object string
 * @param entryPoint - The absolute path to the client file
 * @returns The stub module code
 */
function generateStubModule(
  configObject: string | null,
  entryPoint: string,
): string {
  if (configObject) {
    return `
// Stub module generated by clientStubPlugin
// Only exports buildConfig - browser code is not loaded

export const buildConfig = {
  ...${configObject},
  entryPoint: ${JSON.stringify(entryPoint)},
};
`;
  }

  // No buildConfig found - return legacy stubs for backwards compatibility
  return `
// Stub module for .client.tsx files (legacy - no buildConfig found)
// These functions throw to indicate migration is needed

export const buildConfig = {
  clientDir: 'unknown',
  entryPoint: ${JSON.stringify(entryPoint)},
};

export async function getClientAssetTags() {
  throw new Error(
    'getClientAssetTags stub called - add buildConfig export to this client file'
  );
}

export async function getClientAppManifestInfo() {
  throw new Error(
    'getClientAppManifestInfo stub called - add buildConfig export to this client file'
  );
}
`;
}

/**
 * Plugin that extracts buildConfig from .client.tsx imports.
 *
 * When the server imports a .client.tsx file, this plugin:
 * 1. Reads the file content
 * 2. Extracts the buildConfig using regex
 * 3. Returns a stub module with the config + injected entryPoint
 *
 * This prevents browser code from being loaded on the server while
 * still allowing the server to read the client's build configuration.
 *
 * @example
 * ```typescript
 * // In preload.ts
 * import { clientStubPlugin } from '@inkibra/build-pack';
 * import { plugin } from 'bun';
 *
 * plugin(clientStubPlugin());
 * ```
 *
 * @example
 * ```typescript
 * // In tempo.server.tsx (server-side)
 * import { buildConfig } from './tempo.client.tsx';
 * // buildConfig is extracted, browser code is not loaded
 * ```
 */
export function clientStubPlugin(): BunPlugin {
  return {
    name: 'client-stub-plugin',
    setup(build) {
      // Intercept imports to .client.tsx or .client.ts files
      build.onLoad({ filter: /\.client\.tsx?$/ }, async ({ path }) => {
        // Read the actual file content
        let content: string;
        try {
          content = fs.readFileSync(path, 'utf-8');
        } catch (error) {
          console.warn(`[clientStubPlugin] Could not read file: ${path}`);
          return {
            contents: generateStubModule(null, path),
            loader: 'ts',
          };
        }

        // Extract buildConfig
        const configObject = extractBuildConfig(content);

        if (configObject) {
          console.log(`[clientStubPlugin] Extracted buildConfig from: ${path}`);
        } else {
          console.log(
            `[clientStubPlugin] No buildConfig found in: ${path} (using legacy stubs)`,
          );
        }

        return {
          contents: generateStubModule(configObject, path),
          loader: 'ts',
        };
      });
    },
  };
}
